import {colors} from '../theme/colors';
import {ScriptureCollection} from './types';

const commonBengaliExcludes = [
  'cricket',
  'ipl',
  'football',
  'sports',
  'news',
  'রাজনীতি',
  'politics',
  'bollywood',
  'tollywood',
  'film',
  'cinema',
  'movie',
  'adda',
  'comedy',
  'horror',
  'thriller',
  'crime',
  'business',
  'stock market',
  'tech news',
  'radio mirchi',
  'sunday suspense',
];

const commonLanguageExcludes = [
  'hindi',
  'english',
  'tamil',
  'telugu',
  'malayalam',
  'kannada',
];

export const scriptureCollections: ScriptureCollection[] = [
  {
    id: 'mahalaya-bengali',
    title: 'Mahalaya',
    subtitle: 'Mahishasura Mardini • Bengali',
    description:
      'Birendra Krishna Bhadra\'s legendary pre-dawn recitation that ushers in Devi Paksha.',
    language: 'Bengali',
    tradition: 'Shakta',
    symbol: 'মহা',
    accent: colors.saffron,
    textProvider: 'local-json',
    curatedPodcastShow: {
      id: 'archive-mahalaya-birendra-krishna',
      title: 'Mahalaya Birendra Krishna',
      author: 'Internet Archive',
      feedUrl: 'archive://mahalaya-birendra-krishna',
      genre: 'Archive',
    },
    audioSearchTerms: [
      'mahalaya birendra krishna bhadra',
      'mahishasura mardini',
      'mahalaya bengali',
      'mahalaya bangla',
      'birendra krishna bhadra',
    ],
    audioIncludeTerms: [
      'mahalaya',
      'mahishasura mardini',
      'birendra krishna',
      'bhadra',
    ],
    audioExcludeTerms: [
      ...commonBengaliExcludes,
      'remix',
      'dj',
    ],
    sections: [
      {id: 'mahalaya-invocation', title: 'Invocation', subtitle: 'Opening benediction'},
      {id: 'mahalaya-stotras', title: 'Stotras', subtitle: 'Chandi path and hymns'},
      {id: 'mahalaya-descent', title: 'Devi\'s Descent', subtitle: 'Victory over Mahishasura'},
    ],
  },
  {
    id: 'chandi-path-bengali',
    title: 'Sri Sri Chandi',
    subtitle: 'Devi Mahatmya path • Bengali',
    description:
      'Bengali paath of Sri Sri Chandi with kavach, argala, and Mahalaya-style recitation.',
    language: 'Bengali',
    tradition: 'Shakta',
    symbol: 'দুর্গা',
    accent: colors.lotus,
    textProvider: 'local-json',
    curatedPodcastShow: {
      id: 'archive-saptashati-complete-type-2',
      title: 'Saptashati Audio (Devi Mahatmya)',
      author: 'Internet Archive',
      feedUrl: 'archive://saptashati-complete-type-2',
      genre: 'Archive',
    },
    audioSearchTerms: [
      'sri sri chandi bengali',
      'sri sri chandi bangla',
      'chandi path bengali',
      'chandi path bangla',
      'chandi paath bangla',
      'mahalaya chandi bangla',
      'devi mahatmya bengali',
    ],
    audioIncludeTerms: [
      'sri sri chandi',
      'sri chandi',
      'chandi path',
      'chandipath',
      'durga saptashati',
      'devi mahatmya',
      'mahalaya',
    ],
    audioExcludeTerms: [
      ...commonBengaliExcludes,
      ...commonLanguageExcludes,
      'chandi baba',
      'chandigarh',
      'chandi bar',
    ],
    sections: [
      {id: 'devi-kavach', title: 'Devi Kavach', subtitle: 'Protection and invocation'},
      {id: 'argala-stotram', title: 'Argala Stotram', subtitle: 'Opening praise'},
      {id: 'saptashati', title: 'Saptashati Path', subtitle: 'Main recitation cycle'},
    ],
  },
  {
    id: 'bhagavad-gita',
    title: 'Srimad Bhagavad Gita',
    subtitle: '18 adhyayas • Bengali',
    description:
      'Bengali paath of the Gita with chapter-wise verses, meaning, and devotional commentary.',
    language: 'Bengali',
    tradition: 'Vedanta',
    symbol: 'ॐ',
    accent: colors.saffron,
    textProvider: 'gita-api',
    audioSearchTerms: [
      'bhagavad gita bengali',
      'bhagavad gita bangla',
      'srimad bhagavad gita bangla',
      'srimad bhagavad gita bengali path',
      'gita path bangla',
      'gita paath bengali',
      'gita bengali discourse',
    ],
    audioIncludeTerms: [
      'gita',
      'gita path',
      'bhagavad gita',
      'srimad bhagavad gita',
      'geeta',
    ],
    audioExcludeTerms: [
      ...commonBengaliExcludes,
      ...commonLanguageExcludes,
    ],
    sections: [
      {id: 'gita-1', title: 'Chapters 1-6', subtitle: 'Karma and self-mastery'},
      {id: 'gita-2', title: 'Chapters 7-12', subtitle: 'Bhakti and knowledge'},
      {id: 'gita-3', title: 'Chapters 13-18', subtitle: 'Nature, duty, liberation'},
    ],
  },
  {
    id: 'hanuman-chalisa-bengali',
    title: 'Hanuman Chalisa',
    subtitle: 'Bangla path • Bengali script',
    description:
      'Bengali-script paath of the Hanuman Chalisa with doha, chaupai, and daily devotional recitation.',
    language: 'Bengali',
    tradition: 'Hanuman Bhakti',
    symbol: 'হনু',
    accent: colors.crimson,
    textProvider: 'local-json',
    curatedPodcastShow: {
      id: 'archive-shri-hanuman-chalisa',
      title: 'Shri Hanuman Chalisa',
      author: 'Internet Archive',
      feedUrl: 'archive://ShriHanumanChalisa_404',
      genre: 'Archive',
    },
    audioSearchTerms: [
      'hanuman chalisa bengali',
      'hanuman chalisa bangla',
      'hanuman chalisa bangla path',
      'hanuman chalisa bengali paath',
      'hanuman chalisa bengali script',
      'hanuman chalisa meaning bangla',
    ],
    audioIncludeTerms: [
      'hanuman chalisa',
      'hanuman',
      'chalisa',
      'bajrangbali',
    ],
    audioExcludeTerms: [
      ...commonBengaliExcludes,
      ...commonLanguageExcludes,
      'vivekananda',
      'sarvapriyananda',
      'vedanta',
    ],
    sections: [
      {id: 'chalisa-doha', title: 'Opening Doha', subtitle: 'Invocation and intent'},
      {id: 'chalisa-chaupai', title: '40 Chaupais', subtitle: 'Core recitation'},
      {id: 'chalisa-closing', title: 'Closing Doha', subtitle: 'Prayer and surrender'},
    ],
  },
  {
    id: 'ramayana-krittivasi',
    title: 'Krittivasi Ramayan',
    subtitle: '7 kandas • Bengali',
    description:
      'Krittibas Ojha\'s beloved Bengali Ramayana — Rama\'s journey in Bangla verse.',
    language: 'Bengali',
    tradition: 'Ram Bhakti',
    symbol: 'রাম',
    accent: colors.brand,
    textProvider: 'local-json',
    audioSearchTerms: [
      'krittivasi ramayan bengali',
      'krittibas ramayan bangla',
      'ramayan path bangla',
      'bengali ramayana',
    ],
    audioIncludeTerms: [
      'krittivasi',
      'krittibas',
      'ramayan',
      'ramayana',
    ],
    audioExcludeTerms: [
      ...commonBengaliExcludes,
      ...commonLanguageExcludes,
      'tulsidas',
      'hindi ramayan',
      'valmiki sanskrit only',
    ],
    sections: [
      {id: 'kr-adi', title: 'Adi Kanda', subtitle: 'Origins'},
      {id: 'kr-ayodhya', title: 'Ayodhya Kanda', subtitle: 'Exile begins'},
      {id: 'kr-aranya', title: 'Aranya Kanda', subtitle: 'The forest years'},
      {id: 'kr-kishkindha', title: 'Kishkindha Kanda', subtitle: 'Alliance with Sugriva'},
      {id: 'kr-sundar', title: 'Sundar Kanda', subtitle: 'Hanuman\'s crossing'},
      {id: 'kr-lanka', title: 'Lanka Kanda', subtitle: 'The great war'},
      {id: 'kr-uttar', title: 'Uttar Kanda', subtitle: 'Return and reign'},
    ],
  },
  {
    id: 'ramakrishna-kathamrita',
    title: 'Sri Sri Ramakrishna Kathamrita',
    subtitle: '5 volumes • Bengali',
    description:
      'Mahendranath Gupta\'s record of Sri Ramakrishna\'s conversations at Dakshineswar and Belur.',
    language: 'Bengali',
    tradition: 'Ramakrishna Mission',
    symbol: 'শ্রী',
    accent: colors.brand,
    textProvider: 'local-json',
    audioSearchTerms: [
      'ramakrishna kathamrita bengali',
      'sri sri ramakrishna kathamrita bangla',
      'kathamrita path bangla',
      'belur math kathamrita',
    ],
    audioIncludeTerms: [
      'kathamrita',
      'ramakrishna',
      'sri ramakrishna',
      'belur math',
      'dakshineswar',
    ],
    audioExcludeTerms: [...commonBengaliExcludes, ...commonLanguageExcludes],
    sections: [
      {id: 'kathamrita-1', title: 'Volume 1', subtitle: 'Early conversations at Dakshineswar'},
      {id: 'kathamrita-2', title: 'Volume 2', subtitle: 'Teachings on bhakti and sadhana'},
      {id: 'kathamrita-3', title: 'Volume 3', subtitle: 'Disciples and householders'},
      {id: 'kathamrita-4', title: 'Volume 4', subtitle: 'Deepening discourses'},
      {id: 'kathamrita-5', title: 'Volume 5', subtitle: 'Final years and mahasamadhi'},
    ],
  },
  {
    id: 'belur-math-dakshineswar',
    title: 'Belur Math O Dakshineshwar',
    subtitle: 'Ramakrishna Sangha • Bengali',
    description:
      'Bengali audio journeys through Belur Math, Dakshineshwar, Baranagar, and the history of the Ramakrishna movement.',
    language: 'Bengali',
    tradition: 'Ramakrishna Mission',
    symbol: 'মঠ',
    accent: colors.brand,
    textProvider: 'local-json',
    curatedPodcastShow: {
      id: 'history-of-ramakrishna-movement',
      title: 'History of Ramakrishna Movement (রামকৃষ্ণ সংঘের ইতিবৃত্ত )',
      author: 'Aᴍʀɪᴛᴀᴋᴀʟᴘᴀ',
      feedUrl: 'https://anchor.fm/s/852875b4/podcast/rss',
      genre: 'Religion & Spirituality',
    },
    audioSearchTerms: [
      'belur math bengali',
      'dakshineswar bangla',
      'ramakrishna mission bangla',
      'history of ramakrishna movement',
      'রামকৃষ্ণ সংঘের ইতিবৃত্ত',
      'baranagar math bengali',
    ],
    audioIncludeTerms: [
      'belur math',
      'dakshineswar',
      'ramakrishna mission',
      'ramakrishna movement',
      'baranagar',
      'ramakrishna sangha',
    ],
    audioExcludeTerms: [...commonBengaliExcludes, ...commonLanguageExcludes],
    sections: [
      {id: 'belur-origin', title: 'Dakshineshwar', subtitle: 'Sri Ramakrishna at the temple garden'},
      {id: 'belur-baranagar', title: 'Baranagar Math', subtitle: 'The first monastery and early brotherhood'},
      {id: 'belur-headquarters', title: 'Belur Math', subtitle: 'The permanent monastery on the Ganga'},
      {id: 'belur-sangha', title: 'Sangha Itibritta', subtitle: 'History of the Ramakrishna movement'},
    ],
  },
  {
    id: 'ramakrishna-leela-prasanga',
    title: 'Sri Sri Ramakrishna Leela Prasanga',
    subtitle: 'Swami Saradananda • Bengali',
    description:
      'Swami Saradananda\'s authoritative Bengali biography of Sri Ramakrishna, published from Belur Math.',
    language: 'Bengali',
    tradition: 'Ramakrishna Mission',
    symbol: 'ॐ',
    accent: colors.crimson,
    textProvider: 'local-json',
    audioSearchTerms: [
      'ramakrishna leela prasanga bengali',
      'saradananda leela prasanga bangla',
      'ramakrishna lilaprasanga path',
      'belur math leela prasanga',
    ],
    audioIncludeTerms: [
      'leela prasanga',
      'lila prasanga',
      'lilaprasanga',
      'saradananda',
      'ramakrishna',
    ],
    audioExcludeTerms: [...commonBengaliExcludes, ...commonLanguageExcludes],
    sections: [
      {id: 'leela-sadhak', title: 'Sadhak Bhava', subtitle: 'The spiritual seeker'},
      {id: 'leela-divya', title: 'Divya Bhava', subtitle: 'The divine mood'},
      {id: 'leela-guru', title: 'Guru Bhava', subtitle: 'The teacher and disciples'},
    ],
  },
  {
    id: 'vivekananda-bengali',
    title: 'Swami Vivekananda Rachanabali',
    subtitle: 'Bengali works • Udbodhan, Belur Math',
    description:
      'Swami Vivekananda\'s Bengali letters, lectures, and writings as published by Udbodhan, Belur Math.',
    language: 'Bengali',
    tradition: 'Ramakrishna Mission',
    symbol: 'স্বামী',
    accent: colors.brandBright,
    textProvider: 'local-json',
    curatedPodcastShow: {
      id: 'bibekamrita-nectar-of-vivekananda',
      title: 'বিবেকামৃত _ Nectar of Vivekananda',
      author: 'Aᴍʀɪᴛᴀᴋᴀʟᴘᴀ',
      feedUrl: 'https://anchor.fm/s/10658ac08/podcast/rss',
      genre: 'Books',
    },
    audioSearchTerms: [
      'vivekananda bengali',
      'swami vivekananda bangla',
      'vivekananda rachanabali bangla',
      'বিবেকামৃত',
      'amritakalpa vivekananda',
      'belur math kirtan bengali',
      'belur math bhajan bangla',
      'ramakrishna mission kirtan bangla',
      'udbodhan vivekananda',
      'vivekananda bhashan bangla',
    ],
    audioIncludeTerms: [
      'vivekananda',
      'swami vivekananda',
      'rachanabali',
      'udbodhan',
      'belur math',
      'ramakrishna mission',
      'kirtan',
      'bhajan',
    ],
    audioExcludeTerms: [
      ...commonBengaliExcludes,
      ...commonLanguageExcludes,
      'complete works english',
    ],
    sections: [
      {id: 'viveka-letters', title: 'Patravali', subtitle: 'Letters in Bengali'},
      {id: 'viveka-lectures', title: 'Bhashan O Prabandha', subtitle: 'Lectures and essays'},
      {id: 'viveka-parivrajak', title: 'Parivrajak', subtitle: 'The wandering monk'},
      {id: 'viveka-bhavbar', title: 'Bhavbar Bhavi', subtitle: 'Reflections and teachings'},
    ],
  },
  {
    id: 'upanishad-bengali',
    title: 'Upanishads',
    subtitle: 'Principal Upanishads • Bengali',
    description:
      'Bengali readings and discourses on the principal Upanishads from the Belur Math tradition.',
    language: 'Bengali',
    tradition: 'Vedanta',
    symbol: 'उप',
    accent: colors.teal,
    textProvider: 'local-json',
    audioSearchTerms: [
      'upanishad bengali',
      'upanishad bangla',
      'isha upanishad bangla',
      'katha upanishad bengali',
      'mundaka upanishad bengali',
    ],
    audioIncludeTerms: [
      'upanishad',
      'upanisad',
      'isha upanisad',
      'katha upanisad',
      'mundaka',
      'mandukya',
      'brihadaranyaka',
      'chandogya',
    ],
    audioExcludeTerms: [...commonBengaliExcludes, ...commonLanguageExcludes],
    sections: [
      {id: 'upa-isha', title: 'Isha & Kena', subtitle: 'Foundational meditations'},
      {id: 'upa-katha', title: 'Katha & Prashna', subtitle: 'Dialogues on the Self'},
      {id: 'upa-mundaka', title: 'Mundaka & Mandukya', subtitle: 'Brahman and Om'},
      {id: 'upa-taittiriya', title: 'Taittiriya & Aitareya', subtitle: 'Sheaths and creation'},
      {id: 'upa-chandogya', title: 'Chandogya & Brihadaranyaka', subtitle: 'The great teachings'},
    ],
  },
  {
    id: 'yoga-bengali',
    title: 'Patanjali Yoga Sutra',
    subtitle: '4 padas • Bengali',
    description:
      'Bengali exposition of Patanjali\'s Yoga Sutras — theory and practice of yoga.',
    language: 'Bengali',
    tradition: 'Yoga',
    symbol: 'योग',
    accent: colors.moss,
    textProvider: 'local-json',
    audioSearchTerms: [
      'patanjali yoga sutra bengali',
      'yoga sutra bangla',
      'raja yoga bengali vivekananda',
      'patanjali bangla',
    ],
    audioIncludeTerms: [
      'yoga sutra',
      'patanjali',
      'raja yoga',
      'ashtanga yoga',
    ],
    audioExcludeTerms: [
      ...commonBengaliExcludes,
      ...commonLanguageExcludes,
      'hatha yoga class',
      'yoga workout',
      'yoga with',
      'power yoga',
    ],
    sections: [
      {id: 'yoga-samadhi', title: 'Samadhi Pada', subtitle: 'On contemplation'},
      {id: 'yoga-sadhana', title: 'Sadhana Pada', subtitle: 'On practice'},
      {id: 'yoga-vibhuti', title: 'Vibhuti Pada', subtitle: 'On powers'},
      {id: 'yoga-kaivalya', title: 'Kaivalya Pada', subtitle: 'On liberation'},
    ],
  },
];

export const featuredCollection =
  scriptureCollections.find(collection => collection.id === 'chandi-path-bengali') ??
  scriptureCollections[0];

export function getCollectionById(collectionId: string) {
  return scriptureCollections.find(collection => collection.id === collectionId);
}
